// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqNooDW5jQVXfs3iEkHfkZfm9cgF-o_y8',
    appId: '1:45845320765:web:c02d7743c5d4215d4d4654',
    messagingSenderId: '45845320765',
    projectId: 'e-commerce-d0539',
    authDomain: 'e-commerce-d0539.firebaseapp.com',
    storageBucket: 'e-commerce-d0539.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRCwYoj2HNZwNxrtOMXm4sQOcSSzV3u2E',
    appId: '1:45845320765:android:68f4268f5158146a4d4654',
    messagingSenderId: '45845320765',
    projectId: 'e-commerce-d0539',
    storageBucket: 'e-commerce-d0539.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2dNdoeV1Mpe79cObKdb2nM3mCC6t8S_E',
    appId: '1:45845320765:ios:07fa37d5e3a62d744d4654',
    messagingSenderId: '45845320765',
    projectId: 'e-commerce-d0539',
    storageBucket: 'e-commerce-d0539.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );
}
